[package]
name = "program-launcher"
version = "0.1.0"
authors = ["Juuso Tuononen <jutuon@outlook.com>"]

[dependencies]
glium = "0.17.1"
backend_library = { path = "backend_library"}

[dependencies.conrod]
version = "0.54.0"
features = ["winit", "glium"]

[workspace]